[package]
name = "smol_vlm_video"
version = "0.1.0"
authors = ["Andrew Shen <andrewshen31@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
argh = { workspace = true }
ctrlc = { workspace = true }
gstreamer = "0.24"
gstreamer-app = "0.24"
gstreamer-video = "0.23"
image = "0.25"
kornia = { workspace = true, features = ["v4l"] }
kornia-vlm = { workspace = true }
reqwest = { version = "0.13.2", features = ["blocking"] }
rerun = { workspace = true }

[features]
cuda = ["kornia/cuda"]
