[package]
name = "smol_vlm2_video"
version = "0.1.0"
authors = ["Andrew Shen <andrewshen31@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
argh = { workspace = true }
ctrlc = { workspace = true }
env_logger = { workspace = true }
gstreamer = "0.24.4"
gstreamer-app = "0.24.4"
gstreamer-video = "0.23.6"
kornia = { workspace = true, features = ["v4l"] }
kornia-image = { workspace = true }
kornia-tensor = { workspace = true }
kornia-vlm = { workspace = true }
reqwest = { version = "0.13.2", features = ["blocking"] }
rerun = { workspace = true }

[features]
cuda = ["kornia/cuda"]
